server:
  port: 8080

spring:
  application:
    name: dm-demo
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:5230/LAUGHING
    username: SYSDBA
    password: SYSDBA


